version: 0.2
phases:
  pre_build:
    commands:
      - ECR_PASSWORD=$(aws ecr get-login-password --region $AWS_DEFAULT_REGION)
      - echo $ECR_PASSWORD | docker login --username AWS --password-stdin $AWS_ACCCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - LATEST_IMAGE_TAG="latest"
      - export APP_VERSION=$(git describe --tags --abbrev=0 || echo '0.0')
      - VERSION_IMAGE_TAG="${APP_VERSION}-${CODEBUILD_BUILD_NUMBER}"
      - docker pull ${CONTAINER_REPOSITORY}:${LATEST_IMAGE_TAG} || true
      - docker build --cache-from ${CONTAINER_REPOSITORY}:${LATEST_IMAGE_TAG} --tag ${CONTAINER_REPOSITORY}:${LATEST_IMAGE_TAG} .
  post_build:
    commands:
      - docker push ${CONTAINER_REPOSITORY}:${LATEST_IMAGE_TAG}
      - docker tag ${CONTAINER_REPOSITORY}:${LATEST_IMAGE_TAG} ${CONTAINER_REPOSITORY}:${VERSION_IMAGE_TAG}
      - docker push ${CONTAINER_REPOSITORY}:${VERSION_IMAGE_TAG}
